# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.URLField(max_length=100, unique=True, verbose_name=b'url of reposity of project')),
                ('name_postulation', models.CharField(max_length=50, unique=True, verbose_name=b'name postulation')),
                ('description_postulation', models.TextField(max_length=100, verbose_name=b'description of the postulation')),
                ('status', models.CharField(default=b'Recibido', max_length=20, verbose_name=b'status of postulation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_postulation',),
            },
        ),
    ]
