#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: kit-postulation
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2015 Victor Pino <victopin0@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

case ${1} in

    install|upgrade)
        
	#Si el servicio de apache esta activo lo detenemos para poner correr el server de nginx
	service apache2 stop || true 
	
    ;;

    abort-upgrade|abort-install)

     

    ;;

    *)
            echo "preinst no reconoce el argumento '"${1}"'" >&2
            exit 1
    ;;

esac

#DEBHELPER#

exit 0
